const texts = [

  "Maza Madre: En nuestra pizzería, creemos firmemente que la base de una pizza excepcional radica en una masa madre de calidad superior. Es por eso que hemos perfeccionado nuestro proceso de cultivo y fermentación para ofrecerte una experiencia gastronómica inigualable. Nuestra masa madre es mucho más que un simple ingrediente; es el alma de nuestras pizzas. Cada bocado está impregnado con los sabores complejos y la textura perfecta que solo una fermentación natural puede brindar. La masa madre no solo mejora el sabor y la textura de la masa, sino que también la hace más digerible y nutritiva.",
  "PROCESO DE ELABORACION: Comenzamos con una mezcla de harinas seleccionadas y agua purificada, combinadas con nuestra propia masa madre cultivada durante años. Esta masa madre es el corazón de nuestra receta, infundiendo cada pieza de masa con profundidad de sabor y una textura perfectamente equilibrada. Una vez formada, nuestra masa se deja reposar y fermentar durante horas, permitiendo que los sabores se desarrollen plenamente y la masa adquiera su característica ligereza y esponjosidad. Este proceso lento y meticuloso es fundamental para crear una base excepcional para nuestras pizzas. Finalmente, cada pizza se prepara a mano con cuidado y atención al detalle, antes de ser horneada en nuestro horno de leña tradicional a la perfección dorada. El resultado es una obra maestra culinaria, donde cada bocado te transporta a la auténtica Italia y te deja deseando más. En nuestra pizzería, la calidad nunca es un compromiso, y cada pizza que servimos es un testimonio de nuestro compromiso con la excelencia en cada paso del proceso de elaboración.",
  "LA FASE FINAL: de preparación antes de entregarlas a nuestros apreciados clientes. Con meticulosa atención al detalle, cada pizza es inspeccionada para garantizar que se haya alcanzado la perfección en cada capa de sabor y en cada textura. Desde el crujiente borde de la masa hasta el equilibrio perfecto de ingredientes frescos y sabrosos, cada pizza es sometida a un riguroso estándar de calidad. Una vez confirmada su excelencia, nuestras pizzas son hábilmente empaquetadas, listas para llevar o entregar directamente a tu puerta. Este último proceso representa el momento en que nuestra pasión y compromiso con la excelencia culinaria se materializan en cada deliciosa porción que entregamos. Confía en nosotros para ofrecerte una experiencia gastronómica que superará tus expectativas y te dejará con ganas de más."
  
  
];

export default texts;